version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - agentai-network
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: agentai-server
    ports:
      - "${PORT}:${PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    env_file:
      - ./.env
    depends_on:
      - mongodb
    volumes:
      - ./certs:/app/certs
      - ./logs:/app/logs
    networks:
      - agentai-network
    restart: unless-stopped

  client:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: agentai-client
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    env_file:
      - ./.env
    depends_on:
      - server
    networks:
      - agentai-network
    restart: unless-stopped

networks:
  agentai-network:
    driver: bridge

volumes:
  mongodb_data: