FROM node:20.11.0

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

# Modify app.js to use environment variable for MongoDB connection
RUN sed -i 's|const MONGODB_URL = `mongodb://localhost:27017/gemini`;|const MONGODB_URL = process.env.MONGODB_URL || `mongodb://localhost:27017/gemini`;|g' app.js

EXPOSE 3030

CMD ["npm", "run", "dev"]