// server/utils/agentResponseCombiner.js

/**
 * Combines responses from multiple agents into a single coherent response
 * @param {Object} agentResults - Key-value pairs of agent names and their responses
 * @param {Array} agents - Array of agent objects with id and name properties
 * @param {string} question - The original question asked
 * @returns {Object} Combined result with HTML formatting
 */
export const combineAgentResponses = (agentResults, agents, question) => {
  // Simple case: only one agent response
  if (Object.keys(agentResults).length === 1) {
    const agentName = Object.keys(agentResults)[0];
    return {
      combinedResult: {
        [agentName]: agentResults[agentName],
      },
      formattedHtml: formatSingleAgentResponse(
        question,
        agentName,
        agentResults[agentName]
      ),
    };
  }

  // Multiple agent case: combine results
  const combinedResult = {};

  // Add each agent's result to the combined result
  for (const agentId in agentResults) {
    const agentName = agents.find((a) => a.id === agentId)?.name || agentId;
    combinedResult[agentName] = agentResults[agentId];
  }

  // Format the HTML response for multiple agents
  const formattedHtml = formatMultiAgentResponse(question, combinedResult);

  return { combinedResult, formattedHtml };
};

/**
 * Format a single agent response
 * @param {string} question - Original question
 * @param {string} agentName - Name of the agent
 * @param {string} response - The agent's response
 */
const formatSingleAgentResponse = (question, agentName, response) => {
  return `
    <div class="simple-search-results">
      <h3>Agent Response</h3>
      <p><strong>Query:</strong> "${question}"</p>
      
      <div class="simple-search-content">
        <div class="agent-result">
          <h4>${agentName}</h4>
          <div class="agent-answer">
            ${response}
          </div>
        </div>
      </div>
      
      <div class="simple-search-note">
        <p><small>This response was generated by an AI agent based on your query.</small></p>
      </div>
    </div>
  `;
};

/**
 * Format multiple agent responses
 * @param {string} question - Original question
 * @param {Object} agentResponses - Responses from multiple agents
 */
const formatMultiAgentResponse = (question, agentResponses) => {
  // Create the header
  let html = `
    <div class="simple-search-results">
      <h3>Multi-Agent Response</h3>
      <p><strong>Query:</strong> "${question}"</p>
      
      <div class="agent-badges">
  `;

  // Add agent badges
  for (const agentName in agentResponses) {
    html += `
      <span class="agent-badge">
        <svg class="agent-badge-icon" width="14" height="14" viewBox="0 0 24 24" fill="none">
          <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm0-14c-2.21 0-4 1.79-4 4h2c0-1.1.9-2 2-2s2 .9 2 2c0 2-3 1.75-3 5h2c0-2.25 3-2.5 3-5 0-2.21-1.79-4-4-4z" 
            fill="currentColor"
          />
        </svg>
        ${agentName}
      </span>
    `;
  }

  // Close badges div and begin content section
  html += `
      </div>
      
      <div class="simple-search-content">
  `;

  // Add each agent's response
  for (const agentName in agentResponses) {
    html += `
      <div class="agent-result">
        <h4>${agentName}</h4>
        <div class="agent-answer">
          ${agentResponses[agentName]}
        </div>
      </div>
    `;
  }

  // Add synthesized section if there are multiple agents
  if (Object.keys(agentResponses).length > 1) {
    html += `
      <div class="agent-result synthesized">
        <h4>Synthesized Answer</h4>
        <div class="agent-answer">
          <p>Based on the information from all agents:</p>
          <p>The agents have provided different perspectives on your question. Each agent specializes in different areas, so consider the combined information when making decisions. If you need more specific information from a particular agent, you can select just that agent in your next query.</p>
        </div>
      </div>
    `;
  }

  // Close all divs
  html += `
      </div>
      
      <div class="simple-search-note">
        <p><small>This response was generated by multiple AI agents based on your query.</small></p>
      </div>
    </div>
  `;

  return html;
};

export default combineAgentResponses;
