// server/utils/agentResponseCombiner.js

/**
 * Combines responses from multiple agents into a single coherent response
 * @param {Object} agentResults - Key-value pairs of agent IDs and their responses
 * @param {Array} agents - Array of agent objects with id and name properties
 * @param {string} question - The original question asked
 * @returns {Object} Combined result with HTML formatting
 */
export const combineAgentResponses = (agentResults, agents, question) => {
  // Get agent names mapping
  const agentNames = {};
  agents.forEach((agent) => {
    agentNames[agent.id] = agent.name;
  });

  // Simple case: only one agent response
  if (Object.keys(agentResults).length === 1) {
    const agentId = Object.keys(agentResults)[0];
    const agentName = agentNames[agentId] || agentId;
    return {
      combinedResult: {
        [agentId]: agentResults[agentId],
      },
      formattedHtml: formatSingleAgentResponse(
        question,
        agentName,
        agentResults[agentId]
      ),
    };
  }

  // Multiple agent case: combine results
  const combinedResult = {};

  // Add each agent's result to the combined result
  for (const agentId in agentResults) {
    combinedResult[agentId] = agentResults[agentId];
  }

  // Format the HTML response for multiple agents
  const formattedHtml = formatMultiAgentResponse(
    question,
    agentResults,
    agentNames
  );

  return { combinedResult, formattedHtml };
};

/**
 * Format a response from an agent
 * @param {Object} agentResponse - The agent's response object 
 * @param {string} agentDisplayName - Name of the agent to display
 * @returns {string} Formatted HTML response
 */
export const formatAgentResponse = (agentResponse, agentDisplayName) => {
  // If response is already HTML, return it directly
  if (typeof agentResponse === 'string') {
    return agentResponse;
  }
  
  // If it's a report from deepResearchAgent
  if (agentResponse.report) {
    return `
      <div class="deep-research-results">
        <h3>${agentDisplayName} Results</h3>
        <p><strong>Query:</strong> "${agentResponse.query || 'Unknown query'}"</p>
        
        <div class="research-report">${agentResponse.report}</div>
        
        ${agentResponse.visitedUrls && agentResponse.visitedUrls.length > 0 
          ? `<div class="research-sources">
              <h4>Sources Consulted</h4>
              <ul>
                ${agentResponse.visitedUrls
                  .map(url => `<li><a href="${url}" target="_blank" rel="noopener noreferrer">${url}</a></li>`)
                  .join("")}
              </ul>
            </div>`
          : ''}
        
        <div class="search-follow-up">
          <h4>## Follow-up Questions</h4>
          <div class="gemini-chips-container">
            <div class="gemini-chips">
              <button class="gemini-chip" onclick="document.querySelector('.input-field').value='Tell me more about this topic'; setTimeout(() => document.querySelector('.send-btn').click(), 100);">
                <span class="gemini-chip-text">Tell me more about this topic</span>
              </button>
              <button class="gemini-chip" onclick="document.querySelector('.input-field').value='Can you explain this in simpler terms?'; setTimeout(() => document.querySelector('.send-btn').click(), 100);">
                <span class="gemini-chip-text">Explain this in simpler terms</span>
              </button>
            </div>
          </div>
        </div>
        
        <div class="simple-search-note">
          <p><small>This response was generated by the ${agentDisplayName} based on your query. Results may vary in accuracy and completeness.</small></p>
        </div>
      </div>
    `;
  }
  
  // Generic agent response format
  return `
    <div class="simple-search-results">
      <h3>${agentDisplayName} Response</h3>
      <p><strong>Query:</strong> "${agentResponse.query || 'Unknown query'}"</p>
      
      <div class="simple-search-content">
        <div class="agent-result">
          <div class="agent-answer">
            ${agentResponse.answer || agentResponse.text || 'No response content available'}
          </div>
        </div>
      </div>
      
      ${agentResponse.sources && agentResponse.sources.length > 0
        ? `<div class="search-sources">
            <h4>## Sources</h4>
            <ul>
              ${agentResponse.sources.map((source, index) => 
                `<li>${source.title || source.url || `Source ${index + 1}`}${source.url ? ` - <a href="${source.url}" target="_blank" rel="noopener noreferrer">${source.url}</a>` : ''}</li>`
              ).join('')}
            </ul>
          </div>`
        : ''}
      
      <div class="search-key-points">
        <h4>## Key Points</h4>
        <ul>
          <li>This response was generated by the ${agentDisplayName}</li>
          <li>Different agents may provide different insights</li>
          <li>For more perspectives, try selecting multiple agents</li>
        </ul>
      </div>
      
      <div class="search-follow-up">
        <h4>## Follow-up Questions</h4>
        <div class="gemini-chips-container">
          <div class="gemini-chips">
            <button class="gemini-chip" onclick="document.querySelector('.input-field').value='Tell me more about this'; setTimeout(() => document.querySelector('.send-btn').click(), 100);">
              <span class="gemini-chip-text">Tell me more about this</span>
            </button>
            <button class="gemini-chip" onclick="document.querySelector('.input-field').value='How can I apply this information?'; setTimeout(() => document.querySelector('.send-btn').click(), 100);">
              <span class="gemini-chip-text">How can I apply this information?</span>
            </button>
          </div>
        </div>
      </div>
      
      <div class="simple-search-note">
        <p><small>This response was generated by an AI agent based on your query. Results may vary in accuracy and completeness.</small></p>
      </div>
    </div>
  `;
};

/**
 * Format a single agent response
 * @param {string} question - Original question
 * @param {string} agentName - Name of the agent
 * @param {string} response - The agent's response
 */
const formatSingleAgentResponse = (question, agentName, response) => {
  return `
    <div class="simple-search-results">
      <h3>Agent Response</h3>
      <p><strong>Query:</strong> "${question}"</p>
      
      <div class="simple-search-content">
        <div class="agent-result">
          <h4>${agentName}</h4>
          <div class="agent-answer">
            <h2>## Answer</h2>
            ${response}
          </div>
        </div>
      </div>
      
      <div class="search-key-points">
        <h4>## Key Points</h4>
        <ul>
          <li>This response came from the ${agentName}</li>
          <li>Different agents may provide different insights</li>
          <li>For more perspectives, try selecting multiple agents</li>
        </ul>
      </div>
      
      <div class="search-related-section">
        <h4>## Next Steps</h4>
        <p>You can try:</p>
        <ul>
          <li>Asking a more specific question</li>
          <li>Including more details in your query</li>
          <li>Selecting different agents for other perspectives</li>
        </ul>
      </div>
      
      <div class="search-follow-up">
        <h4>## Follow-up Questions</h4>
        <div class="gemini-chips-container">
          <div class="gemini-chips">
            <button class="gemini-chip" onclick="document.querySelector('.input-field').value='Tell me more about ${encodeURIComponent(
              question
            )}'; setTimeout(() => document.querySelector('.send-btn').click(), 100);">
              <span class="gemini-chip-icon">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
                  <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" 
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
              </span>
              <span class="gemini-chip-text">Tell me more about this</span>
            </button>
            <button class="gemini-chip" onclick="document.querySelector('.input-field').value='How can I troubleshoot this?'; setTimeout(() => document.querySelector('.send-btn').click(), 100);">
              <span class="gemini-chip-icon">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
                  <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" 
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
              </span>
              <span class="gemini-chip-text">How can I troubleshoot this?</span>
            </button>
          </div>
        </div>
      </div>
      
      <div class="simple-search-note">
        <p><small>This response was generated by an AI agent based on your query. Results may vary in accuracy and completeness.</small></p>
      </div>
    </div>
  `;
};

/**
 * Format multiple agent responses
 * @param {string} question - Original question
 * @param {Object} agentResponses - Responses from multiple agents
 * @param {Object} agentNames - Mapping of agent IDs to human-readable names
 */
const formatMultiAgentResponse = (question, agentResponses, agentNames) => {
  // Create the header
  let html = `
    <div class="simple-search-results">
      <h3>Multi-Agent Response</h3>
      <p><strong>Query:</strong> "${question}"</p>
      
      <div class="simple-search-content">
  `;

  // Add each agent's response
  for (const agentId in agentResponses) {
    const displayName = agentNames[agentId] || agentId;
    html += `
      <div class="agent-result">
        <h4>${displayName}</h4>
        <div class="agent-answer">
          ${agentResponses[agentId]}
        </div>
      </div>
    `;
  }

  // Add key points section
  html += `
      <div class="search-key-points">
        <h4>## Key Points</h4>
        <ul>
          <li>Multiple agents have provided responses to your query</li>
          <li>Each agent specializes in different areas of expertise</li>
          <li>Consider all perspectives when evaluating the information</li>
          <li>For more specific information, you can select individual agents</li>
        </ul>
      </div>
  `;

  // Add next steps section
  html += `
      <div class="search-related-section">
        <h4>## Next Steps</h4>
        <p>You can try:</p>
        <ul>
          <li>Ask a follow-up question to get more details</li>
          <li>Try asking a more specific question</li>
          <li>Select fewer agents for more focused responses</li>
        </ul>
      </div>
  `;
      
  // Add follow-up questions section
  html += `
      <div class="search-follow-up">
        <h4>## Follow-up Questions</h4>
        <div class="gemini-chips-container">
          <div class="gemini-chips">
            <button class="gemini-chip" onclick="document.querySelector('.input-field').value='Tell me more about ${encodeURIComponent(
              question
            )}'; setTimeout(() => document.querySelector('.send-btn').click(), 100);">
              <span class="gemini-chip-icon">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
                  <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" 
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
              </span>
              <span class="gemini-chip-text">Tell me more about this</span>
            </button>
            <button class="gemini-chip" onclick="document.querySelector('.input-field').value='What are the alternatives?'; setTimeout(() => document.querySelector('.send-btn').click(), 100);">
              <span class="gemini-chip-icon">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
                  <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" 
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
              </span>
              <span class="gemini-chip-text">What are the alternatives?</span>
            </button>
          </div>
        </div>
      </div>
  `;

  // Close all divs
  html += `
      </div>
      
      <div class="simple-search-note">
        <p><small>This response was generated by multiple AI agents based on your query. Results may vary in accuracy and completeness.</small></p>
      </div>
    </div>
  `;

  return html;
};

export default combineAgentResponses;